" Initialize:
" 1. Windows(nvim):
"   md ~\AppData\Local\nvim\autoload
"   $uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
"   (New-Object Net.WebClient).DownloadFile(
"     $uri,
"     $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(
"       "~\AppData\Local\nvim\autoload\plug.vim"
"     )
"   )
" 2. Linux:
"   curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" neovim 配置目录:  ~/.config/nvim/
" let &packpath = &runtimepath

let s:config_files = [
         \ '~/.vim/option.vim',
         \ '~/.vim/plugin.vim',
         \ '~/.vim/mapping.vim',
         \]

function s:load_config()
  for l:filename in s:config_files
    execute 'source ' . expand(l:filename)
  endfor
endfunction

call s:load_config()
