# load user config
source ~/.user_config.zsh

# curl -L git.io/antigen > antigen.zsh
source ~/antigen.zsh

# Load oh-my-zsh library
antigen use oh-my-zsh

# Load bundles from the default repo (oh-my-zsh)
antigen bundle git
antigen bundle command-not-found
antigen bundle extract
antigen bundle autojump
antigen bundle cp
antigen bundle colored-man-pages
antigen bundle safe-paste # 复制脚本后不会立即运行
antigen bundle autopep8
antigen bundle python
antigen bundle rust
antigen bundle rustup
antigen bundle cargo
antigen bundle tmux
antigen bundle pip
antigen bundle sudo

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen theme robbyrussell

antigen apply


# core dump location
# ulimit -c unlimited
# echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern
